plot_params:
  im_path: "images"

data_params:
  batch_size: 5
  shuffle: True
  num_workers: null
  prefetch_factor: null
  persistent_workers: null
  pin_memory: null
  dask_threads: 4

main_params:
  source: "gcs"
  num_epochs: 2
  num_batches: 3
  batch_size: 16
  shuffle: null
  num_workers: null
  prefetch_factor: null
  persistent_workers: null
  pin_memory: null
  train_step_time: 0.1
  dask_threads: null

